# Generated by Django 3.0.4 on 2020-04-04 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('desc', models.TextField(blank=True, max_length=2500, null=True)),
                ('clearance', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(blank=True, default='', max_length=250, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(blank=True, default=False)),
                ('isAuthenticated', models.BooleanField(default=True)),
                ('joined_on', models.DateField(default=django.utils.timezone.now)),
                ('online', models.BooleanField(default=False)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('primary_color', models.CharField(default='#8115C4', max_length=10)),
                ('secondary_color', models.CharField(default='#e67a63', max_length=10)),
                ('location', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('occupation', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('tag', models.CharField(blank=True, default='', max_length=1200, null=True)),
                ('bio', models.TextField(blank=True, default='', max_length=2400, null=True)),
                ('avatar', models.ImageField(blank=True, default='avatars/DEFAULT/dressedAvatar-300x516.png', null=True, upload_to=users.models.User.upload_to_avatar_dir)),
                ('avatar_thumbnail', models.ImageField(blank=True, default='avatars/DEFAULT/thumbnail/avatar-120x120.png', null=True, upload_to=users.models.User.upload_to_thumbnail_dir)),
                ('display_profile_snackbar', models.BooleanField(default=True)),
                ('display_full_name', models.BooleanField(default=False)),
                ('display_date_of_birth', models.BooleanField(default=False)),
                ('display_location', models.BooleanField(default=False)),
                ('display_occupation', models.BooleanField(default=False)),
                ('IS_ANONYMOUS', models.BooleanField(default=False)),
                ('dailyChance', models.BooleanField(default=True)),
                ('dailyChanceDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('friends', models.ManyToManyField(blank=True, related_name='_user_friends_+', to=settings.AUTH_USER_MODEL)),
                ('interests', models.ManyToManyField(blank=True, to='users.Interest')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Role')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='wallet.Wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
