# Generated by Django 3.0.4 on 2020-04-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_class', models.CharField(default='', max_length=50)),
                ('quantity_sold', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
