# Generated by Django 3.0.4 on 2020-04-04 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='FullSizeNPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=250)),
                ('alt', models.CharField(blank=True, default='', max_length=250)),
                ('created_on_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('activated_on_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deactivated_on_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='main/images/NPC')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeaderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=250)),
                ('alt', models.CharField(blank=True, default='', max_length=250)),
                ('created_on_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('activated_on_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deactivated_on_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='main/images/header')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
