# Generated by Django 3.0.4 on 2020-04-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200404_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullsizenpc',
            name='dialogue',
            field=models.ManyToManyField(blank=True, to='main.Dialogue'),
        ),
    ]
