# Generated by Django 3.0.4 on 2020-04-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shinies', models.IntegerField(default=0)),
                ('muns', models.IntegerField(default=0)),
            ],
        ),
    ]
