# Generated by Django 3.0.4 on 2020-04-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='owner',
            field=models.CharField(default='', max_length=50),
        ),
    ]
