# Generated by Django 3.0.4 on 2020-04-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default='', max_length=2400),
        ),
        migrations.AlterField(
            model_name='comment',
            name='published_on_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
