# Generated by Django 3.0.4 on 2020-04-04 22:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20200404_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published_on_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
